// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMFoCWBRkj_WtffgmtzgVYqMzihSS_dp8',
    appId: '1:598990146660:web:6d8d25c4aa6c14a5f8a371',
    messagingSenderId: '598990146660',
    projectId: 'bracelet-app-7d36b',
    authDomain: 'bracelet-app-7d36b.firebaseapp.com',
    databaseURL: 'https://bracelet-app-7d36b-default-rtdb.firebaseio.com',
    storageBucket: 'bracelet-app-7d36b.firebasestorage.app',
    measurementId: 'G-0PLL4HZB57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM4D5P0QJpYlSpEetWgGus3_9yIBFehT8',
    appId: '1:598990146660:android:d8cc753eb19db2d3f8a371',
    messagingSenderId: '598990146660',
    projectId: 'bracelet-app-7d36b',
    databaseURL: 'https://bracelet-app-7d36b-default-rtdb.firebaseio.com',
    storageBucket: 'bracelet-app-7d36b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVlh2tpV0INfIShby0SLE0m3RpdYiRhLI',
    appId: '1:598990146660:ios:e1a16b968742f68df8a371',
    messagingSenderId: '598990146660',
    projectId: 'bracelet-app-7d36b',
    databaseURL: 'https://bracelet-app-7d36b-default-rtdb.firebaseio.com',
    storageBucket: 'bracelet-app-7d36b.firebasestorage.app',
    iosBundleId: 'com.example.alzheimerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVlh2tpV0INfIShby0SLE0m3RpdYiRhLI',
    appId: '1:598990146660:ios:e1a16b968742f68df8a371',
    messagingSenderId: '598990146660',
    projectId: 'bracelet-app-7d36b',
    databaseURL: 'https://bracelet-app-7d36b-default-rtdb.firebaseio.com',
    storageBucket: 'bracelet-app-7d36b.firebasestorage.app',
    iosBundleId: 'com.example.alzheimerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMFoCWBRkj_WtffgmtzgVYqMzihSS_dp8',
    appId: '1:598990146660:web:fe5db47b86726f3cf8a371',
    messagingSenderId: '598990146660',
    projectId: 'bracelet-app-7d36b',
    authDomain: 'bracelet-app-7d36b.firebaseapp.com',
    databaseURL: 'https://bracelet-app-7d36b-default-rtdb.firebaseio.com',
    storageBucket: 'bracelet-app-7d36b.firebasestorage.app',
    measurementId: 'G-9GBZ5T2CNR',
  );
}
